//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "logical_expression")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub group_id: i32,
    pub kind: i16,
    pub data: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::fingerprint::Entity")]
    Fingerprint,
    #[sea_orm(
        belongs_to = "super::group::Entity",
        from = "Column::GroupId",
        to = "super::group::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Group,
    #[sea_orm(has_many = "super::logical_children::Entity")]
    LogicalChildren,
}

impl Related<super::fingerprint::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fingerprint.def()
    }
}

impl Related<super::logical_children::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LogicalChildren.def()
    }
}

impl Related<super::group::Entity> for Entity {
    fn to() -> RelationDef {
        super::logical_children::Relation::Group.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::logical_children::Relation::LogicalExpression
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
