//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub table_id: i32,
    pub name: String,
    pub compression_method: String,
    pub r#type: i32,
    pub base_attribute_number: i32,
    pub is_not_null: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attribute_constraint_junction::Entity")]
    AttributeConstraintJunction,
    #[sea_orm(has_many = "super::attribute_foreign_constraint_junction::Entity")]
    AttributeForeignConstraintJunction,
    #[sea_orm(has_many = "super::statistic_to_attribute_junction::Entity")]
    StatisticToAttributeJunction,
    #[sea_orm(
        belongs_to = "super::table_metadata::Entity",
        from = "Column::TableId",
        to = "super::table_metadata::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TableMetadata,
}

impl Related<super::attribute_constraint_junction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeConstraintJunction.def()
    }
}

impl Related<super::attribute_foreign_constraint_junction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeForeignConstraintJunction.def()
    }
}

impl Related<super::statistic_to_attribute_junction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StatisticToAttributeJunction.def()
    }
}

impl Related<super::table_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TableMetadata.def()
    }
}

impl Related<super::statistic::Entity> for Entity {
    fn to() -> RelationDef {
        super::statistic_to_attribute_junction::Relation::Statistic.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::statistic_to_attribute_junction::Relation::Attribute
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
