//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "attribute_stat")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub number_of_attributes: i32,
    pub epoch_id: i32,
    pub name: String,
    pub created_time: DateTimeUtc,
    pub stats_type: i32,
    pub stats_value: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attribute_stats_junction::Entity")]
    AttributeStatsJunction,
    #[sea_orm(
        belongs_to = "super::event::Entity",
        from = "Column::EpochId",
        to = "super::event::Column::EpochId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Event,
}

impl Related<super::attribute_stats_junction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeStatsJunction.def()
    }
}

impl Related<super::event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Event.def()
    }
}

impl Related<super::table_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        super::attribute_stats_junction::Relation::TableAttribute.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::attribute_stats_junction::Relation::AttributeStat
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
