//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "column")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub table_id: i32,
    pub name: String,
    pub compression_method: String,
    pub r#type: i32,
    pub base_col_number: i32,
    pub is_not_null: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::column_constraint_junction::Entity")]
    ColumnConstraintJunction,
    #[sea_orm(has_many = "super::column_foreign_constraint_junction::Entity")]
    ColumnForeignConstraintJunction,
    #[sea_orm(has_many = "super::column_statistic_to_column_junction::Entity")]
    ColumnStatisticToColumnJunction,
    #[sea_orm(
        belongs_to = "super::table_metadata::Entity",
        from = "Column::TableId",
        to = "super::table_metadata::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TableMetadata,
}

impl Related<super::column_constraint_junction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ColumnConstraintJunction.def()
    }
}

impl Related<super::column_foreign_constraint_junction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ColumnForeignConstraintJunction.def()
    }
}

impl Related<super::column_statistic_to_column_junction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ColumnStatisticToColumnJunction.def()
    }
}

impl Related<super::table_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TableMetadata.def()
    }
}

impl Related<super::column_statistic::Entity> for Entity {
    fn to() -> RelationDef {
        super::column_statistic_to_column_junction::Relation::ColumnStatistic.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::column_statistic_to_column_junction::Relation::Column
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
