//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "constraint_attribute_junction")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub constraint_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub attr_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::constraint::Entity",
        from = "Column::ConstraintId",
        to = "super::constraint::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Constraint,
    #[sea_orm(
        belongs_to = "super::table_attribute::Entity",
        from = "Column::AttrId",
        to = "super::table_attribute::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TableAttribute,
}

impl Related<super::constraint::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Constraint.def()
    }
}

impl Related<super::table_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TableAttribute.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
