//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "database_metadata")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub creation_time: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::namespace_metadata::Entity")]
    NamespaceMetadata,
}

impl Related<super::namespace_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NamespaceMetadata.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
