//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub epoch_id: i32,
    pub source_variant: String,
    pub create_timestamp: DateTimeUtc,
    pub data: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attribute_stat::Entity")]
    AttributeStat,
    #[sea_orm(has_many = "super::cost::Entity")]
    Cost,
    #[sea_orm(has_many = "super::group_winner::Entity")]
    GroupWinner,
}

impl Related<super::attribute_stat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeStat.def()
    }
}

impl Related<super::cost::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cost.def()
    }
}

impl Related<super::group_winner::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupWinner.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
