//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "group")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub group_id: i64,
    pub winner: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::logical_expression::Entity")]
    LogicalExpression,
    #[sea_orm(has_many = "super::logical_property::Entity")]
    LogicalProperty,
}

impl Related<super::logical_expression::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LogicalExpression.def()
    }
}

impl Related<super::logical_property::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LogicalProperty.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
