//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "index_metadata")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub table_id: i32,
    pub name: String,
    pub number_of_attributes: i32,
    pub variant_tag: i32,
    pub is_unique: bool,
    pub nulls_not_distinct: bool,
    pub is_primary: bool,
    pub is_clustered: bool,
    pub is_exclusion: bool,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::constraint_metadata::Entity")]
    ConstraintMetadata,
    #[sea_orm(
        belongs_to = "super::table_metadata::Entity",
        from = "Column::TableId",
        to = "super::table_metadata::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TableMetadata,
}

impl Related<super::constraint_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConstraintMetadata.def()
    }
}

impl Related<super::table_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TableMetadata.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
