//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "logical_property")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub data: Json,
    pub group_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cascades_group::Entity",
        from = "Column::GroupId",
        to = "super::cascades_group::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CascadesGroup,
}

impl Related<super::cascades_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CascadesGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
