//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "logical_expression")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub fingerprint_id: i32,
    pub data: Json,
    pub group_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fingerprint::Entity",
        from = "Column::FingerprintId",
        to = "super::fingerprint::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Fingerprint,
    #[sea_orm(
        belongs_to = "super::group::Entity",
        from = "Column::GroupId",
        to = "super::group::Column::GroupId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Group,
}

impl Related<super::fingerprint::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fingerprint.def()
    }
}

impl Related<super::group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Group.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
