//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod cascades_group;
pub mod column;
pub mod column_constraint_junction;
pub mod column_foreign_constraint_junction;
pub mod column_statistic;
pub mod column_statistic_to_column_junction;
pub mod constraint;
pub mod database_metadata;
pub mod event;
pub mod group_winner;
pub mod index;
pub mod logical_expression;
pub mod logical_group_junction;
pub mod logical_property;
pub mod namespace_metadata;
pub mod physical_expression;
pub mod physical_group_junction;
pub mod physical_property;
pub mod plan_cost;
pub mod table_metadata;
pub mod trigger;
