//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod cascades_group;
pub mod database_metadata;
pub mod logical_expression;
pub mod logical_group_junction;
pub mod logical_property;
pub mod namespace_metadata;
pub mod physical_expression;
pub mod physical_group_junction;
pub mod physical_property;
pub mod table_metadata;
