//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "table_metadata")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub create_time: DateTimeUtc,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::namespace_metadata::Entity",
        from = "Column::Id",
        to = "super::namespace_metadata::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    NamespaceMetadata,
}

impl Related<super::namespace_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NamespaceMetadata.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
