//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "table_metadata")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub schema_id: i32,
    pub name: String,
    pub created_time: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::index::Entity")]
    Index,
    #[sea_orm(
        belongs_to = "super::namespace_schema::Entity",
        from = "Column::SchemaId",
        to = "super::namespace_schema::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    NamespaceSchema,
    #[sea_orm(has_many = "super::table_attribute::Entity")]
    TableAttribute,
    #[sea_orm(has_many = "super::trigger::Entity")]
    Trigger,
}

impl Related<super::index::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Index.def()
    }
}

impl Related<super::namespace_schema::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NamespaceSchema.def()
    }
}

impl Related<super::table_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TableAttribute.def()
    }
}

impl Related<super::trigger::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trigger.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
