//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "versioned_statistic")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub epoch_id: i32,
    pub statistic_id: i32,
    pub statistic_value: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event::Entity",
        from = "Column::EpochId",
        to = "super::event::Column::EpochId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Event,
    #[sea_orm(
        belongs_to = "super::statistic::Entity",
        from = "Column::StatisticId",
        to = "super::statistic::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Statistic,
}

impl Related<super::event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Event.def()
    }
}

impl Related<super::statistic::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Statistic.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
